config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users do
    get :change_permission, on: :member
  end
  resources :sessions
  get 'users/new'

  resources :posts do
    get :favourite, on: :member
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
  get 'auth/vkontakte/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_create :build_default_profile
  has_one :profile
  has_many :posts, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  has_many :account, dependent: :destroy
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  self.per_page = 8
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  private

  def build_default_profile
    build_profile
    puts 'profile has been added'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :authorize, only: [:index, :destroy]
  before_action :require_admin, only: [:index, :destroy]

  def index
    @users = User.all 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def require_admin
    redirect_to root_path unless current_user.try(:admin?)
    flash[:success] = "You admin?"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
      @user.update(admin: !@user.admin)
      redirect_to :back
    end

  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/users_helper.rb
#
module UsersHelper
end

app/views/users/edit.html.erb
<div id="page_wrapper">
  <center><h1>Update your profile</h1></center>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :Name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Last_name %><br />
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
     <p>
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: 'my_class' %>
    </p>
    <p class="buttons"><%= f.submit %></p>
  <% end %>
</div>

app/views/users/index.html.erb
<div id="page_wrapper">
  <b><center>All Users</center></b>
  <br>
    <table class="table table-bordered">
      <tr>
        <td>№</td>
        <td>User</td>
        <td>Email</td>
        <td>Avatar</td>
        <td>Make</td>
      </tr>
      <% @users.each do |user| %>
        <div class="user_wrapper">
          <tr>
            <td><%=user.id%></td>
            <td><%=link_to user.name + " " + user.lastname, user %></td>
            <td><%=user.email%></td>
            <td><%=image_tag user.avatar.url(:avat), class: "img-circle"%></td>
            <td>
              <% if user.admin %>
              <%= link_to 'user', change_permission_user_path(user), class: "label label-primary"%>
              <% else %>
              <%= link_to 'admin', change_permission_user_path(user), class: "label label-danger" %>
              <% end %>
            </td>
          </tr>
        </div>
      <% end %>
    </table>
  <p><center><%= will_paginate @users %></center></p>
</div>

app/views/users/new.html.erb
<div id="page_wrapper">
  <center><h1>Sign Up</h1></center>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :Name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Last_name %><br />
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
     <p>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </p>
    <p>
      <i class="fa fa-vk fa-2x"></i>
    </p>
    <p class="buttons"><%= f.submit %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid well span6">
  <center><h1>My Profile</h1></center>
  <center>
  <div class="row-fluid">
    <div class="span2" >
      <%= image_tag current_user.avatar.url(:avat) , class: "img-circle"%>
    </div>
  </center>
    <center>
      <div class="span8">
          <h3><%= @user.name %> <%= @user.lastname %></h3>
          <h6><i class="glyphicon glyphicon-envelope"></i> <%= current_user.email %></h6>
      </div>
      <button type="buttonss" class="btn btn-primary"><%= link_to 'Edit_user', edit_user_path(@user) %></button> 
    </center>
  </div>
</div>