config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users do
    get :change_permission, on: :member
  end
  resources :sessions
  get 'users/new'

  resources :posts do
    get :favourite, on: :member
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
  get 'auth/vkontakte/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/comment.rb
#
class Comment < ActiveRecord::Base
  validates :user_id, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/favourite_post.rb
class FavouritePost < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def self.manage(post)
    object = find_by(post: post)
    object ? object.destroy : create(post: post)
  end

end

app/models/post.rb
#
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :favourite_posts
  belongs_to :user
  has_and_belongs_to_many :categories
  validates :title, presence: true, length: { minimum: 5 }
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  self.per_page = 2
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_create :build_default_profile
  has_one :profile
  has_many :posts, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  has_many :account, dependent: :destroy
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  self.per_page = 8
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  private

  def build_default_profile
    build_profile
    puts 'profile has been added'
  end
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/comments_controller.rb
#
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body, :avatar))
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/omniauth_controller.rb
#
class OmniauthController < ApplicationController
  before_action :current_resources

  def create
    
    if @user
    @account[user: @user]
    else
    @user = @account.create_user(vk_params)
    end
    @account.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private

  def current_resources
    @account = Account.find_or_create_by(uid: auth_hash[:uid],provider: auth_hash[:provider],email: auth_hash[:info][:email])
    @user = User.find_by(email: auth_hash[:info][:email])
  end

  def vk_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
    {
    email: auth_hash[:info][:email],
    remote_avatar_url: auth_hash[:extra][:raw_info][:photo_200],
    password: password,
    password_confirmation: password
    }
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
#
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
#
class PostsController < ApplicationController
  before_action :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories).order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    puts "------>#{@post.user_id}"
    if @post.save
      puts "------>#{@post.user_id}"
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post.increment!(:page_views)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def favourite
    current_user.favourite_posts.manage(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, category_ids: [])
  end

  def current_post
    @post = Post.find(params[:id])
  end

  def require_user
    redirect_to root_path unless current_user == @post.user 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
      @user.update(admin: !@user.admin)
      redirect_to :back
    end

  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
#
module ApplicationHelper
end

app/helpers/comments_helper.rb
#
module CommentsHelper
end

app/helpers/pages_helper.rb
#
module PagesHelper
end

app/helpers/posts_helper.rb
# Posts helper
module PostsHelper
  def require_user
  current_user == @post.user
  end

  def favourite_post(post)
    if current_user && current_user.favourite_posts.map(&:post).include?(post)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/sessions_helper.rb
#
module SessionsHelper
end

app/helpers/users_helper.rb
#
module UsersHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/admin/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="sidebar">
      <%= render 'shared/sidebar' %>
    </div>
    <div id="main_content">
      <%= render 'shared/header' %>
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "15.jpg" %>
  </div>
  <div id="content">
    <h1>Hey, I'm Pedorenko Andrey </h1>
    <p>Welcome to my blog</p>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quibusdam laborum, quas eligendi possimus veritatis sed perferendis nobis earum fugit minus laboriosam voluptas, doloribus modi voluptates distinctio blanditiis et labore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, minus dolor aliquam saepe, consectetur quibusdam expedita. Odio fugit recusandae reprehenderit consequatur quae, porro fuga, maxime, dolor deleniti illo adipisci velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio illo fugiat commodi, deleniti! Dolorum esse velit magni placeat voluptas, enim excepturi eligendi quasi quibusdam qui ex saepe officiis soluta, iure. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius amet minus laudantium possimus id doloremque ducimus ex voluptate eaque officia debitis architecto nemo quaerat dolorum, fuga ut esse? Similique, obcaecati.
    </p>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="buttons">
  <% if current_user %>
    <%= image_tag current_user.avatar.url(:avat), class: "img-circle" %>
    Logged in as <%= current_user.email %>.
  <% if current_user.try(:admin?) %>
    <p>Admin</p>
  <% else %>
    <p>User</p>
  <% end %>
  <button class="button"><%= link_to "Log out", log_out_path %></button>
    <% else %>
      <button class="button"><%= link_to "Sign up", sign_up_path %></button> or
      <button class="button"><%= link_to "log in", log_in_path %></button>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="logo", class: "img-rounded">
  <%= link_to root_path do %>
    <%= image_tag "logo.jpg",  class: "img-circle" %>
  <% end %>
</div>
<ul>
  <li><i class="fa fa-home"></i><%= link_to "Home",  root_path %></li>
  <li><i class="fa fa-plus-circle"></i><%= link_to "New post",  new_post_path %></li>
  <li><i class="fa fa-crosshairs"></i><%= link_to "About", about_path  %></li>
  <li><i class="fa fa-user"></i><%= link_to "My Profile", current_user %></li>
  <% if current_admin %>
    <li><i class="fa fa-plus-circle"></i><%= link_to "Admin",  admin_root_path %></li>
  <% end %>
</ul>
<div class="icons">
  <ul class="social-icons">
     <li><a href="https://www.facebook.com/pedorenko.andriu"><span class="fa fa-facebook"></span></a></li>
     <li><a href="http://vk.com/a.pedorenko"><span class="fa fa-vk"></span></a></li>
     <li><a href="#"><span class="fa fa-instagram"></span></a></li>
     <li><a href="https://plus.google.com/u/0/117005286675324655417"><span class="fa fa-google-plus"></span></a></li>
     <li><a href="https://github.com/development1995"><span class="fa fa-github"></span></a></li>
  </ul>
</div>

app/views/shared/admin/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Admin', '#', class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Back to site', root_path %></li>
        <li><%= link_to 'Users', admin_users_path %></li>
        <li><%= link_to 'Posts', admin_posts_path %></li>
      </ul>
    </div>
  </div>
</nav>