config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users do
    get :change_permission, on: :member
  end
  resources :sessions
  get 'users/new'

  resources :posts do
    get :favourite, on: :member
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
  get 'auth/vkontakte/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  
  
end

app/models/post.rb
#
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :favourite_posts
  belongs_to :user
  has_and_belongs_to_many :categories
  validates :title, presence: true, length: { minimum: 5 }
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  self.per_page = 2
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminsController
  before_action :authorize, only: [:index, :destroy]
  before_action :require_admin, only: [:index, :destroy]

  def index
    @posts = Post.all 
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def require_admin
    redirect_to root_path unless current_user.try(:admin?)
    flash[:success] = "You admin?"
  end
end

app/controllers/posts_controller.rb
#
class PostsController < ApplicationController
  before_action :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories).order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    puts "------>#{@post.user_id}"
    if @post.save
      puts "------>#{@post.user_id}"
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post.increment!(:page_views)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def favourite
    current_user.favourite_posts.manage(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, category_ids: [])
  end

  def current_post
    @post = Post.find(params[:id])
  end

  def require_user
    redirect_to root_path unless current_user == @post.user 
  end
end

app/helpers/posts_helper.rb
# Posts helper
module PostsHelper
  def require_user
  current_user == @post.user
  end

  def favourite_post(post)
    if current_user && current_user.favourite_posts.map(&:post).include?(post)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><% msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
   <p>
    <%= f.label :category_ids %><br>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/posts/favourite.js.erb
$('#post_<%= @post.id %>').toggleClass('text-danger').toggleClass('text-muted');

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %D, %Y") %></p>
    <p><b>Category:</b>
    <% post.categories.each do |category| %>
      <%= category.name %>
    <% end %></p>
    <p class="image"><%= image_tag post.image.url(:thumb), class: "img-rounded" %></p>
    <% if current_user %>
      <%= link_to favourite_post_path(post), id: "post_#{post.id}", class: favourite_post(post), remote: true do %>
        <span>Like <i class = "glyphicon glyphicon-star-empty"></i></span>
      <% end %>
    <% end %>
  </div>
<% end %>
<p><center><%= will_paginate @posts %></center></p>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Новый пост</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <center><%= @post.title %></center>
  </h1>
  <div class="row">
    <div class="col-md-2">
      <p><center><%= image_tag @post.user.avatar.url(:avat), class: "img-circle" %> </center></p>
      <p><center><%= @post.user.email %></center></p>
    </div>
    <div class="col-md-10">
      <p class="body">
        <p class="date">
          Submitted <%= time_ago_in_words(@post.created_at)%> Ago
          <% if require_user %>
            <%= link_to 'Edit', edit_post_path(@post),class: "label label-warning" %>
            <%= link_to 'Delete', post_path(@post),class: " label label-danger", method: :delete, data: { confirm: 'Are you sure' } %>
          <% end %> 
        </p>
        <%= @post.body %> 
        <p class = "image">
          <%= image_tag @post.image.url(:medium),  class: "img-rounded" %>
        </p>
    </div> 
  </div>
    <div class="row">
      <div class="col-md-2">

      </div>
      <div class="col-md-5">
        <p>Количество просмотров: <%=  @post.page_views %></p>
      </div>
      <div class="col-md-5">
        <p align="right">
          <i class = "glyphicon glyphicon-star-empty"></i>
          <%= @post.favourite_posts.count %>
        </p>
      </div>
    </div>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>